import { PoolDTO } from '../dto/sandbox-instance/pool-dto';
import { SandboxDefinitionDTO } from '../dto/sandbox-definition/sandbox-definition-dto';
import { SandboxInstanceDTO } from '../dto/sandbox-instance/sandbox-instance-dto';
import { RequestDTO } from '../dto/sandbox-instance/request-dto';
import { SandboxAllocationUnitDTO } from '../dto/sandbox-instance/sandbox-allocation-unit-dto';
import { CloudResourceDTO } from '../dto/sandbox-instance/stages/cloud-resource-dto';
import { VirtualImageDTO } from '../dto/vm-images/virtual-image-d-t-o';
import { LockDTO } from '../dto/sandbox-instance/lock-dto';
import { SandboxDefinitionRefDTO } from '../dto/sandbox-definition/sandbox-definition-ref-dto';

export type PoolSort = keyof PoolDTO;
export type SandboxDefinitionSort = keyof SandboxDefinitionDTO;
export type SandboxDefinitionRefSort = keyof SandboxDefinitionRefDTO;
export type SandboxInstanceSort = keyof SandboxInstanceDTO;
export type AllocationRequestSort = keyof RequestDTO;
export type AllocationUnitSort = keyof SandboxAllocationUnitDTO;
export type ResourceUsageSort = keyof CloudResourceDTO;
export type VmImageSort = keyof VirtualImageDTO;
export type PoolLockSort = keyof LockDTO;
export type AllocationOutputSort = 'content';
